name: Deploy DemoPay

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy To EC2

        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            cd ~/linkpos-demopay || git clone https://github.com/Shubhamj2405/linkpos-demopay.git

            cd ~/linkpos-demopay

            git pull origin main

            docker compose down

            docker compose up -d --build